### PR TITLE
Method `save_if_dirty` created

### PR DESCRIPTION
**Pull request by ihoru**
And `save_dirty_fields` start saving only if any field is dirty

This method calls parent's (from Model) save method only if any field is dirty (even any from passed `update_fields`)

### CODE REVIEW

**Comment by romgar** [comment]
@ihoru can you write a test for it please?

What are you trying to achieve? You would like to pass a list of fields to update on `save_dirty_fields` if they are dirty?

**Comment by ihoru** [comment]
1. First case (most common):
Call `save_if_dirty()` without args to save model only if anything changed

2. Second case:
Call `save_if_dirty(update_fields=['field_name'])` to save model if these fields have changed.

Could you please help me to set up test? Then I will write test cases.

**Comment by romgar** [comment]
Your first case is exactly what `save_dirty_fields()` is covering, isn't it?

For your second case, we could add a parameter to `save_dirty_fields()` to specify the fields we want to update, if dirty.

To setup the test environment, create a new virtualenv, install tox (`pip install tox`) and run it (`tox`).

**Comment by ihoru** [comment]
Actually, you are right! I double checked some moments and decided that I was wrong.

**Comment by romgar** [comment]
@ihoru you still had one use case that is not handled by `save_dirty_fields`, where we could specify which fields we want to update.

**Comment by ihoru** [comment]
@romgar yep, you a right!

**Pull request closed without merging**
