### PR TITLE
Support disable_dirtyfields on queryset

### PR DESCRIPTION
**Pull request by YAmikep**
Related to: https://github.com/romgar/django-dirtyfields/issues/132
I would love your insights on this and maybe a better solution?

Notes:
- works on Python 3.6.0 and `Django==1.11.5`
- does NOT currently support `prefetch_related` but supports `select_related`.

### CODE REVIEW

**Comment by romgar** [comment]
I have no better solution for now. I'm fine to integrate this MR after a bit of cleaning and ensuring that we can use this manager only with a specific version of Django (and documenting it)

**Comment by YAmikep** [comment]
Great, thanks for the updates.

**Comment by spumer** [comment]
Any updates guys?

**Comment by romgar** [comment]
@YAmikep motivated to do this cleaning and ensure that the manager is only available for this specific version of Django?

**Comment by LincolnPuzey** [comment]
Closing since I have documented a better solution in #193

**Pull request closed without merging**
